version: "3.7"
services:
  postgres:
    image: postgres:14.2
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data/
volumes:
  postgres-data: {}
